apiVersion: v1
kind: ConfigMap
metadata:
  name: pre-sync-config
  namespace: {{ .Values.namespace }}
data:
  ARGOCD_APP_NAME: "{{ .Values.preSyncJob.env.appName }}"
  ARGOCD_REPO_URL: "{{ .Values.preSyncJob.env.repoUrl }}"
  WEBHOOK_HOST: "{{ .Values.preSyncJob.env.webhookHost }}"
  WEBHOOK_PORT: "{{ .Values.preSyncJob.env.webhookPort }}"

