apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-config
  namespace: webhook
data:
  application.yaml: |
    entityTypeId: bank_users
    resourceType: bank_users
    plainIdEndpoint: http://my-plainid-paa-runtime.yaniv-namespace.svc.cluster.local:80/api/runtime/permit-deny/v3
    action: Access

