clientId: PJMBO9FCTONFJ8EDYWT7
clientSecret: JZ6gerPR3SWCugXOmHhtsuMZZnkkclS26o43XSDN
entityTypeId: Leumi_Array_Identity
resourceType: EP_ROLE_TEST
plainIdEndpoint: http://my-plainid-paa-runtime.yaniv-namespace.svc.cluster.local:80/api/runtime/permit-deny/v3
